### PR TITLE
Adding a custom protest sign to supermarket

### PR DESCRIPTION
**Pull request by poulpito**
linked with #109 

Custom Propsign ytd/ytyp so we do not touch the original sign

### CODE REVIEW

**Review by NariieL — APPROVED** [review]

**Review by NariieL — APPROVED** [review]
Approved

**Comment by joelwurtz** [comment]
Same as https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/pull/95

Can you add the image to the folder ? And squash + rebase your commits ? (also please make sur you don't have any lint issue with lua or typescript)

**Comment by poulpito** [comment]
All modifications done

**Comment by joelwurtz** [comment]
Mergé dans https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/commit/c7d4740d4baebd16ac47253c298e30a337a1c9ae merci à toi

**Pull request closed without merging**
