### PR TITLE
New ubmrella item based on walkstick

### PR DESCRIPTION
**Pull request by poulpito**
linked with #94

### CODE REVIEW

**Review by NariieL — APPROVED** [review]
Trop bien le parapluie !

**Comment by joelwurtz** [comment]
There is a new way of handling images by directly putting the png into the `resources/[soz]/soz-core/public/images/items` folder instead of having to update the ytd file, can you rebase and add your image there ?

Also can you fix lua code style, rebase your pr and squash it ? il would really help us merging this feature ❤️

**Comment by poulpito** [comment]
Rebase & squash 
 for lua-format maybe i've a problem with my config ... on the "no new line" 
does not raise and error on my side.

**Comment by poulpito** [comment]
all modifications done

**Comment by joelwurtz** [comment]
Mergé dans https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/commit/0b26f98b9bf61b3f1446ef973d0fa3d8a8413238 merci à toi

**Pull request closed without merging**
