### PR TITLE
refactor(map/cayo) : add native name instead of raw call

### PR DESCRIPTION
**Pull request by Mathu-lmn**
See https://docs.fivem.net/natives/?_0xF74B1FFA4A15FBEA

### CODE REVIEW

**Comment by Laikker** [comment]
Thanks for your proposal, it has been implemented on the main repo during a rework of the cayo perico map

**Comment by Mathu-lmn** [comment]
Can't seem to find the rework you mention :/ Is it public ?

**Comment by Laikker** [comment]
> Can't seem to find the rework you mention :/ Is it public ?

not yet

**Comment by Mathu-lmn** [comment]
Ah right, I'll close my PRs then

**Comment by NariieL** [comment]
> Ah right, I'll close my PRs then

I'm going to update the OSS. :)

**Pull request closed without merging**
