### PR TITLE
refactor(native): replaced all GetPlayerPed(-1)

### PR DESCRIPTION
**Pull request by spacevx**
Issue #61 
Every GetPlayerPed(-1) as been replaced by PlayerPedId(), since PlayerPedId() is more faster than GetPlayerPed(-1), btw according to the Lua Styleguide of qb-core (qb-core/contributing.md) developers should use PlayerPedId()

<a href="https://forum.cfx.re/t/question-difference-between-getplayerped-1-and-playerpedid/539437">Difference between the natives</a>

### CODE REVIEW

**Comment by NariieL** [comment]
Your improvement cannot be taken in consideration at the moment.

🚂 You must first open an improvement proposal using the "Improvement" template available in the Issues.
image

**Comment by spacevx** [comment]
> Your improvement cannot be taken in consideration at the moment.
> 
> 🚂 You must first open an improvement proposal using the "Improvement" template available in the Issues. image

Srry, should be good now #61

**Comment by joelwurtz** [comment]
Mergé dans https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/commit/a8edc6e53c5315552e5a8729da44f9d5bed9ab26

**Comment by joelwurtz** [comment]
Merci beaucoup la PR, ca reste une optimisation même si je pense pas qu'on y gagne beaucoup

**Pull request closed without merging**
